// Sign-in / sign-up popup copy.
export const AUTH = {
  heading: 'Get started with your email',
  subheading: 'Free to start. No card required.',
  namePlaceholder: 'Your full name',
  continue: 'Continue',
  back: 'Use a different email',
  loginHeading: 'Welcome back',
  passwordLabel: 'Password',
  passwordPlaceholder: '••••••••',
  confirmLabel: 'Confirm password',
  signIn: 'Sign in',
  createAccount: 'Create account',
  forgot: 'Forgot password?',
  forgotHeading: 'Reset your password',
  forgotSubheading: 'Enter your email and we’ll send a reset link.',
  sendReset: 'Send reset link',
  confirmHeading: 'Check your email',
  confirmBody: (email: string) => `We sent a link to ${email}. Click it to verify your email, then you’ll set your password.`,
  resetHeading: 'Check your email',
  resetBody: (email: string) => `If ${email} has an account, a password reset link is on its way.`,
  notConfirmed: 'Your email isn’t confirmed yet - check your inbox for the link.',
  badCredentials: 'Incorrect password. Forgot it - or signed up with Google? Use “Forgot password?” below to set or reset it.',
  setupHeading: 'Finish setting up',
  setupSubheading: 'Add your name and a password to secure your account.',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@example.com',
  continueWithGoogle: 'Continue with Google',
  orDivider: 'or',
  resend: 'Resend link',
  changeEmail: 'Use a different email',
  termsNote: 'By continuing you agree to our',
  terms: 'Terms',
  privacy: 'Privacy Policy',
  whyJoinTitle: 'Why join Immigroov?',
} as const;
