export interface Quote { text: string; author: string }

// Shown in the login popup. A random one is picked each time the popup opens.
// Thirukkural couplets use the W.H. Drew & John Lazarus translation; couplet numbers
// verified against that edition. Naladiyar uses G.U. Pope.
export const QUOTES: Quote[] = [
  { text: "Whatever the nature of a thing may be, discerning its true essence is true wisdom.", author: "Kural 355 (trans. W.H. Drew & John Lazarus)" },
  { text: "Learn thoroughly, and let your conduct reflect your learning.", author: "Kural 391 (trans. W.H. Drew & John Lazarus)" },
  { text: "Numbers and letters are the two true eyes of all living beings.", author: "Kural 392 (trans. W.H. Drew & John Lazarus)" },
  { text: "The learned alone are said to possess eyes; the unlearned have but two sores.", author: "Kural 393 (trans. W.H. Drew & John Lazarus)" },
  { text: "Those who humbly seek knowledge, achieve greatness; the unlearned remain inferior.", author: "Kural 395 (trans. W.H. Drew & John Lazarus)" },
  { text: "Knowledge flows in proportion to learning, just as water flows in proportion to depth.", author: "Kural 396 (trans. W.H. Drew & John Lazarus)" },
  { text: "Since every country and every town can be his own, why would a man remain unlearned?", author: "Kural 397 (trans. W.H. Drew & John Lazarus)" },
  { text: "Learning is the only true and imperishable wealth.", author: "Kural 400 (trans. W.H. Drew & John Lazarus)" },
  { text: "Wealth gained by the ear is the chief of all wealth.", author: "Kural 411 (trans. W.H. Drew & John Lazarus)" },
  { text: "When there is no food for the ear, let a little be given to the stomach.", author: "Kural 412 (trans. W.H. Drew & John Lazarus)" },
  { text: "Listen to the wise, however little; it yields great dignity.", author: "Kural 416 (trans. W.H. Drew & John Lazarus)" },
  { text: "Wisdom is a weapon to ward off destruction; it is an inner fortress that enemies cannot destroy.", author: "Kural 421 (trans. W.H. Drew & John Lazarus)" },
  { text: "Wisdom is discerning the truth in everything, regardless of who speaks it.", author: "Kural 423 (trans. W.H. Drew & John Lazarus)" },
  { text: "The wise foresee what is to come; the unwise do not.", author: "Kural 427 (trans. W.H. Drew & John Lazarus)" },
  { text: "Those who possess wisdom, possess everything; those who have not wisdom, whatever they may possess, have nothing.", author: "Kural 430 (trans. W.H. Drew & John Lazarus)" },
  { text: "Winning the alliance of the great is the rarest of blessings.", author: "Kural 443 (trans. W.H. Drew & John Lazarus)" },
  { text: "The stalks of lotus grow according to the depth of the water; greatness grows with the depth of thinking.", author: "Kural 595 (trans. W.H. Drew & John Lazarus)" },
  { text: "Always aim for greatness; even if you fail, the noble intent remains.", author: "Kural 596 (trans. W.H. Drew & John Lazarus)" },
  { text: "Never slacken in your work; the world abandons those who leave a task unfinished.", author: "Kural 612 (trans. W.H. Drew & John Lazarus)" },
  { text: "Adversity is no disgrace; to be without exertion and ignorance, is a disgrace.", author: "Kural 618 (trans. W.H. Drew & John Lazarus)" },
  { text: "Even when fate opposes you, sheer effort will always yield its reward.", author: "Kural 619 (trans. W.H. Drew & John Lazarus)" },
  { text: "They who labour on without fear will see fate put behind their backs.", author: "Kural 620 (trans. W.H. Drew & John Lazarus)" },
  { text: "The mother who hears her son called wise will rejoice more than she did at his birth.", author: "Kural 69 (trans. W.H. Drew & John Lazarus)" },
  { text: "It is more pleasant to hold the dart that has missed an elephant than that which has hit a hare.", author: "Kural 772 (trans. W.H. Drew & John Lazarus)" },
  { text: "What is learned is a handful; what is unlearned is the size of the world.", author: "Avvaiyar (Kattrathu Kaimann Alavu)" },
  { text: "Seek your fortune even if you must cross the oceans.", author: "Avvaiyar (Thiraikadal odiyum thiraviyam thedu)" },
  { text: "A learned person is honored wherever they go.", author: "Avvaiyar (Katroruku sendra idamellam sirapu)" },
  { text: "Aim high! Better miss a lion, than hit a jackal.", author: "Naladiyar (trans. G.U. Pope)" },
  { text: "Peace is learning's gift: that is the only true beauty.", author: "Naladiyar (trans. G.U. Pope)" },
  { text: "The wise think of the special benefits they have received from others, while the fool keeps himself only in his own mind.", author: "Naladiyar (trans. G.U. Pope)" },
  { text: "All towns are our own, everyone our kin", author: "Purananuru 192" },
  { text: "Help given without expecting anything in return is more valuable than heaven and earth.", author: "Kural 101 (trans. W.H. Drew & John Lazarus)" },
  { text: "The true value of a favor is measured not by the favor itself, but by the character of the receiver.", author: "Kural 105 (trans. W.H. Drew & John Lazarus)" },
  { text: "Never forget the kindness of good people, and never abandon the friends who supported you in hard times.", author: "Kural 106 (trans. W.H. Drew & John Lazarus)" },
  { text: "To meet with joy and part with the eager thought of meeting again is the mark of the learned.", author: "Kural 394 (trans. W.H. Drew & John Lazarus)" },
  { text: "Even without formal education, fill your ears with knowledge; it will be your steadfast support in hard times.", author: "Kural 414 (trans. W.H. Drew & John Lazarus)" },
  { text: "The advice of good people is like a walking stick on slippery ground.", author: "Kural 415 (trans. W.H. Drew & John Lazarus)" },
  { text: "Carefully recognize the worth of those with mature knowledge and virtue, and secure their guidance.", author: "Kural 441 (trans. W.H. Drew & John Lazarus)" },
  { text: "A leader without the guidance of those who can correct them will fall, even without enemies.", author: "Kural 448 (trans. W.H. Drew & John Lazarus)" },
  { text: "It is rare to find modest speech in those who have not received subtle and profound instruction.", author: "Kural 419 (trans. W.H. Drew & John Lazarus)" },
  { text: "Those who possess the wisdom to foresee and guard against future evils will never be struck by shocking disasters.", author: "Kural 429 (trans. W.H. Drew & John Lazarus)" },
  { text: "Just as there is no profit for those without capital, there is no stability for those who lack the support of wise.", author: "Kural 449 (trans. W.H. Drew & John Lazarus)" },
  { text: "Abandoning the friendship of the good is ten times worse than making enemies of a multitude.", author: "Kural 450 (trans. W.H. Drew & John Lazarus)" },
  { text: "Calculate the cost, the potential outcome, and the ultimate profit before undertaking any action.", author: "Kural 461 (trans. W.H. Drew & John Lazarus)" },
  { text: "An undertaking executed without the proper method will fail, even if supported by a multitude of people.", author: "Kural 468 (trans. W.H. Drew & John Lazarus)" },
  { text: "Even after learning all theoretical methods, one must understand the practical ways of the world to act successfully.", author: "Kural 636 (trans. W.H. Drew & John Lazarus)" },
  { text: "Carefully consider these five elements—capital, tools, time, action, and place—and clear away all doubts before acting.", author: "Kural 675 (trans. W.H. Drew & John Lazarus)" },
  { text: "The best method to accomplish a task is to seek out and absorb the knowledge of one who already knows its intricacies.", author: "Kural 677 (trans. W.H. Drew & John Lazarus)" },
  { text: "Speak your knowledge clearly before the learned, and absorb knowledge from those who are more learned than you.", author: "Kural 714 (trans. W.H. Drew & John Lazarus)" },
  { text: "The learning a person acquires in one lifetime will stand by them and protect them through seven future births.", author: "Kural 398 (trans. W.H. Drew & John Lazarus)" },
  { text: "Seeing that their learning brings joy to the world, the wise are motivated to love learning even more.", author: "Kural 399 (trans. W.H. Drew & John Lazarus)" },
];

export function randomQuote(): Quote {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
