export interface Riddle { question: string; answer: string }

// Shown on the "rate limited" popup while the user waits out a short (per-minute) Groq
export const RIDDLES: Riddle[] = [
  { question: 'What has keys but no locks, space but no room, and you can enter but not go in?', answer: 'A keyboard.' },
  { question: 'The more you take, the more you leave behind. What am I?', answer: 'Footsteps.' },
  { question: 'What gets wetter the more it dries?', answer: 'A towel.' },
  { question: 'I have cities but no houses, mountains but no trees, and water but no fish. What am I?', answer: 'A map.' },
  { question: 'I have wings but no feathers, and I fly but am not alive. What am I?', answer: 'An airplane.' },
  { question: 'What goes through cities and fields, but never moves?', answer: 'A road.' },
  { question: 'I can take you to places you\'ve never been, but I stay in the corner. What am I?', answer: 'A postage stamp.' },
  { question: 'I point the way but never move. What am I?', answer: 'A compass.' },
  { question: 'I open doors for you but have no hands. What am I?', answer: 'A key.' },
  { question: 'You pack me up, but I am never full. What am I?', answer: 'A suitcase.' },
  { question: 'I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?', answer: 'An echo.' },
  { question: 'I am bought by the yard and worn by the foot. What am I?', answer: 'A carpet.' },
  { question: 'I have hands but cannot clap. What am I?', answer: 'A clock.' },
  { question: 'I am full of holes but still hold water. What am I?', answer: 'A sponge.' },
  { question: 'You answer me, although I never ask you questions. What am I?', answer: 'A telephone.' },
  { question: 'The more of this there is, the less you see. What is it?', answer: 'Darkness.' },
  { question: 'I have branches, but no fruit, trunk, or leaves. What am I?', answer: 'A bank.' },
  { question: 'What has to be broken before you can use it?', answer: 'An egg.' },
  { question: 'I am always in front of you but can never be seen. What am I?', answer: 'The future.' },
  { question: 'I belong to you, but other people use me more than you do. What am I?', answer: 'Your name.' },
  { question: 'What goes up but never comes down?', answer: 'Your age.' },
  { question: 'I can run but never walk. I have a mouth but never talk. What am I?', answer: 'A river.' },
  { question: 'What has one eye but cannot see?', answer: 'A needle.' },
  { question: 'What has many rings but no fingers?', answer: 'A tree.' },
  { question: 'I am easy to lift but hard to throw. What am I?', answer: 'A feather.' },
  { question: 'What can you hold in your right hand, but never in your left hand?', answer: 'Your left hand.' },
  { question: 'You can drop me from the tallest building and I will be fine, but if you drop me in water I die. What am I?', answer: 'Paper.' },
  { question: 'I start with T, end with T, and have T in me. What am I?', answer: 'A teapot.' },
  { question: 'What stamp gets you into a new country but cannot mail a letter?', answer: 'A visa.' },
  { question: 'What has a neck but no head?', answer: 'A bottle.' },
  { question: 'I am an instrument that you can hear but never touch or see. What am I?', answer: 'Your voice.' },
  { question: 'What has words, but never speaks?', answer: 'A book.' },
  { question: 'What gets bigger the more you take away?', answer: 'A hole.' },
  { question: 'I am as light as a feather, yet the strongest person cannot hold me for five minutes. What am I?', answer: 'Breath.' },
  { question: 'What comes once in a minute, twice in a moment, but never in a thousand years?', answer: 'The letter M.' },
  { question: 'I am a bird, I am a fruit, and I am a person from a specific country. What am I?', answer: 'A Kiwi.' },
  { question: 'What has a head and a tail but no body?', answer: 'A coin.' },
  { question: 'I am tall when I am young, and I am short when I am old. What am I?', answer: 'A pencil.' },
  { question: 'What document tells your past to secure your future?', answer: 'A resume.' },
  { question: 'If you have me, you want to share me. If you share me, you haven\'t got me. What am I?', answer: 'A secret.' },
  { question: 'What can you catch but not throw?', answer: 'A cold.' },
  { question: 'Forward I am heavy, backward I am not. What am I?', answer: 'The word Ton.' },
  { question: 'I have teeth but cannot bite. What am I?', answer: 'A comb.' },
  { question: 'I can open doors in foreign lands without being a physical key. What am I?', answer: 'Language.' },
  { question: 'I shrink every time I take a step, but I leave a mark of where I have been. What am I?', answer: 'Chalk.' },
  { question: 'I change when you cross an ocean, though I am not a clock. What am I?', answer: 'A time zone.' },
  { question: 'I have walked the path you are on, and my job is to make your walk easier. What am I?', answer: 'A mentor.' },
  { question: 'What has a bottom at the top?', answer: 'Your legs.' },
  { question: 'What is black when it is clean and white when it is dirty?', answer: 'A chalkboard.' },
  { question: 'You carry me across borders to prove who you are, but I am just a small book. What am I?', answer: 'A passport.' },
  { question: 'What building has the most stories?', answer: 'The library.' },
  { question: 'What has many keys but cannot open a single door?', answer: 'A piano.' },
  { question: 'What goes up and down but doesn\'t move?', answer: 'A staircase.' },
  { question: 'What has a thumb and four fingers, but is not a hand?', answer: 'A glove.' },
  { question: 'What runs around the whole yard without moving?', answer: 'A fence.' },
  { question: 'What loses its head in the morning and gets it back at night?', answer: 'A pillow.' },
  { question: 'What is always coming but never arrives?', answer: 'Tomorrow.' },
  { question: 'What can you break, even if you never pick it up or touch it?', answer: 'A promise.' },
  { question: 'What is so fragile that saying its name breaks it?', answer: 'Silence.' },
  { question: 'What begins with an E and ends with an E, but only contains one letter?', answer: 'An envelope.' },
  { question: 'What gets sharper the more you use it?', answer: 'A brain.' },
  { question: 'I am a word of five letters; if you take away two, only one remains. What word am I?', answer: 'Stone.' },
  { question: 'Give me food, and I will live; give me water, and I will die. What am I?', answer: 'Fire.' },
  { question: 'What kind of coat can only be put on wet?', answer: 'A coat of paint.' },
  { question: 'What goes up when rain comes down?', answer: 'An umbrella.' },
  { question: 'If an electric train is traveling south, which way is the smoke blowing?', answer: 'There is no smoke on an electric train.' },
  { question: 'What month of the year has 28 days?', answer: 'All of them.' },
  { question: 'What has a head, a tail, is brown, and has no legs?', answer: 'A penny.' },
  { question: 'Where does today come before yesterday?', answer: 'In the dictionary.' },
  { question: 'What invention lets you look right through a wall?', answer: 'A window.' },
  { question: 'What has four legs but cannot walk?', answer: 'A table.' },
  { question: 'What can pass through a window without breaking it?', answer: 'Light.' },
  { question: 'What is made of water, but if you put it into water it dies?', answer: 'An ice cube.' },
  { question: 'What goes through a door but never goes in or out?', answer: 'A keyhole.' },
  { question: 'What can you keep after giving it to someone else?', answer: 'Your word.' }
];

// Shuffle so the order differs each time the popup opens.
export function shuffledRiddles(): Riddle[] {
  const a = [...RIDDLES];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
